### PR TITLE
HAI-1050 Remove Keycloak

### PR DESCRIPTION
**Pull request by corvidian**
# Description

Haitaton has transiotined completely over to using Helsinki Profiili instead of our own Keycloak instance. It can be now removed.

## Type of change

- [ ] Bug fix 
- [ ] New feature 
- [X] Other

# Checklist:

- [ ] I have written new tests (if applicable)
- [ ] I have ran the tests myself (if applicable)
- [ ] I have made necessary changes to the documentation, link to confluence
 or other location:

### CODE REVIEW

**Comment by corvidian** [comment]
Waiting for Platta to remove the pipelines.

**Comment by pitkni** [comment]
I know this is a draft, but .env.local seems to have a reference to haitaton-auth-data.

**Comment by corvidian** [comment]
> I know this is a draft, but .env.local seems to have a reference to haitaton-auth-data.

Thank you, my searches didn't reveal that one.

**Comment by corvidian** [comment]
The pipelines were removed, so we can remove Keycloak from the project as well now.

**Review by pitkni — APPROVED** [review]

**Pull request merged**
